name: HACS Action

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  hacs:
    runs-on: "ubuntu-latest"
    name: HACS Action
    steps:
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"